use_frameworks!

target 'WPHTTPMonitor_Example' do
  pod 'WPHTTPMonitor', :path => '../'

  target 'WPHTTPMonitor_Tests' do
    inherit! :search_paths

    pod 'Kiwi'
  pod 'FBSnapshotTestCase'
  end
end
